#!/usr/bin/env bash
#lista best school until
namefile=school
if [ -e $namefile ]; then
		echo "$namefile file exists"

			if [ -s $namefile ]; then
						echo "$namefile file is not empty"
							else 
									echo "$namefile file is empty"
										fi
											
											if [ -f $namefile ]; then
													echo "$namefile is a regular file"
														fi
													else
															echo "$namefile file does not exist"
fi
