#!/usr/bin/env bash
#You cannot use ps
#!/usr/bin/env bash
trap "echo I hate the kill command; rm -r /var/run/myscript.pid; exit" 15
trap "echo Y U no love me?!" 2
trap "rm -r /var/run/myscript.pid; exit" 3

while :
do
echo "$$" > /var/run/myscript.pid
echo "To infinity and beyond"
sleep 2
done
